export const DEMO_ACTIVITIES = [
  {
    id: 'demo-1',
    title: 'Go for a run in the park',
    description: 'Enjoy nature and get some exercise by running in your local park.',
    category: 'Sport',
    duration: 60,
    locationType: 'Outdoor',
    costType: 'Free',
    difficulty: 'Medium',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-2',
    title: 'Read a book',
    description: 'Pick up that book you\'ve been meaning to read and dive in.',
    category: 'Relaxation',
    duration: 120,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-3',
    title: 'Visit a local museum',
    description: 'Learn something new by exploring exhibits at a nearby museum.',
    category: 'Education',
    duration: 180,
    locationType: 'Indoor',
    costType: 'Paid',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-4',
    title: 'Try a new recipe',
    description: 'Find an interesting recipe online and cook it for dinner.',
    category: 'Creativity',
    duration: 90,
    locationType: 'Indoor',
    costType: 'Paid',
    difficulty: 'Medium',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-5',
    title: 'Go hiking',
    description: 'Find a trail and enjoy the great outdoors.',
    category: 'Outdoor',
    duration: 240,
    locationType: 'Outdoor',
    costType: 'Free',
    difficulty: 'Hard',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-6',
    title: 'Watch a classic movie',
    description: 'Pick a highly rated classic film and enjoy it with popcorn.',
    category: 'Entertainment',
    duration: 150,
    locationType: 'Indoor',
    costType: 'Paid',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-7',
    title: 'Do a home workout',
    description: 'Follow a yoga or HIIT video online.',
    category: 'Sport',
    duration: 45,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Medium',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-8',
    title: 'Learn to juggle',
    description: 'Grab three objects and look up a tutorial.',
    category: 'Education',
    duration: 30,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Hard',
    rating: 3,
    isCustom: false,
  }
];
