export const DEMO_ACTIVITIES = [
  {
    id: 'demo-1',
    title: 'Пробіжка в парку',
    description: 'Насолодіться природою та потренуйтеся, бігаючи у місцевому парку.',
    category: 'Спорт',
    duration: 60,
    locationType: 'На вулиці',
    costType: 'Безкоштовно',
    difficulty: 'Середньо',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-2',
    title: 'Почитати книгу',
    description: 'Візьміть книгу, яку давно хотіли прочитати, і пориньте в неї.',
    category: 'Відпочинок',
    duration: 120,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-3',
    title: 'Відвідати місцевий музей',
    description: 'Дізнайтеся щось нове, досліджуючи експонати в сусідньому музеї.',
    category: 'Навчання',
    duration: 180,
    locationType: 'В приміщенні',
    costType: 'Платно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-4',
    title: 'Спробувати новий рецепт',
    description: 'Знайдіть цікавий рецепт в інтернеті та приготуйте його на вечерю.',
    category: 'Креативність',
    duration: 90,
    locationType: 'В приміщенні',
    costType: 'Платно',
    difficulty: 'Середньо',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-5',
    title: 'Піти в похід',
    description: 'Знайдіть стежку і насолоджуйтесь чудовою природою.',
    category: 'На вулиці',
    duration: 240,
    locationType: 'На вулиці',
    costType: 'Безкоштовно',
    difficulty: 'Складно',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-6',
    title: 'Подивитися класичний фільм',
    description: 'Оберіть класичний фільм з високим рейтингом і насолоджуйтесь ним з попкорном.',
    category: 'Розваги',
    duration: 150,
    locationType: 'В приміщенні',
    costType: 'Платно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-7',
    title: 'Домашнє тренування',
    description: 'Виконайте йогу або HIIT-тренування за відео з інтернету.',
    category: 'Спорт',
    duration: 45,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Середньо',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-8',
    title: 'Навчитися жонглювати',
    description: 'Візьміть три предмети і знайдіть навчальне відео.',
    category: 'Навчання',
    duration: 30,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Складно',
    rating: 3,
    isCustom: false,
  },
  {
    id: 'demo-9',
    title: 'Послухати подкаст',
    description: 'Знайдіть цікавий епізод подкасту і дізнайтеся щось нове під час відпочинку.',
    category: 'Навчання',
    duration: 30,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-10',
    title: '10-хвилинна медитація',
    description: 'Посидьте в тиші, зосередьтеся на диханні та очистіть свій розум.',
    category: 'Відпочинок',
    duration: 10,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-11',
    title: 'Швидка розтяжка',
    description: 'Зніміть напругу, зробивши комплексну розтяжку для всього тіла.',
    category: 'Спорт',
    duration: 15,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-12',
    title: 'Помалювати або зробити скетч',
    description: 'Візьміть олівець і папір та намалюйте те, що спаде на думку.',
    category: 'Креативність',
    duration: 20,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-13',
    title: 'Коротка прогулянка кварталом',
    description: 'Подихайте свіжим повітрям під час швидкої прогулянки надворі.',
    category: 'На вулиці',
    duration: 20,
    locationType: 'На вулиці',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-14',
    title: 'Попити чай у тиші',
    description: 'Заваріть чашку чаю і випийте її без будь-яких відволікань.',
    category: 'Відпочинок',
    duration: 15,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-15',
    title: 'Пограти у браузерну гру',
    description: 'Знайдіть безкоштовну гру в браузері і пограйте кілька хвилин.',
    category: 'Розваги',
    duration: 20,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 3,
    isCustom: false,
  },
  {
    id: 'demo-16',
    title: 'Записати 3 цілі',
    description: 'Знайдіть хвилинку, щоб записати три речі, яких ви хочете досягти цього тижня.',
    category: 'Креативність',
    duration: 10,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-17',
    title: 'Планка',
    description: 'Станьте в планку на одну хвилину, щоб зміцнити м\'язи преса.',
    category: 'Спорт',
    duration: 1,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Середньо',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-18',
    title: '30 присідань',
    description: 'Швидко виконайте 30 присідань для тонусу м\'язів ніг.',
    category: 'Спорт',
    duration: 2,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Середньо',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-19',
    title: 'Розминка шиї та плечей',
    description: 'Легкі кругові рухи, щоб зняти напругу після роботи за комп\'ютером.',
    category: 'Спорт',
    duration: 3,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-20',
    title: 'Вивчити нове слово',
    description: 'Знайдіть та запам\'ятайте одне нове слово іноземною мовою.',
    category: 'Навчання',
    duration: 1,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-21',
    title: 'Цікавий науковий факт',
    description: 'Прочитайте один випадковий науковий факт у мережі.',
    category: 'Навчання',
    duration: 2,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-22',
    title: 'Стаття у Вікіпедії',
    description: 'Прочитайте вступну частину випадкової статті у Вікіпедії.',
    category: 'Навчання',
    duration: 3,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-23',
    title: 'Швидкий скетч',
    description: 'Намалюйте першу річ, яку бачите перед собою, за 1 хвилину.',
    category: 'Креативність',
    duration: 1,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-24',
    title: '3 ідеї для бізнесу',
    description: 'Швидко запишіть три будь-які ідеї, які спали вам на думку.',
    category: 'Креативність',
    duration: 2,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-25',
    title: 'Написати короткий вірш',
    description: 'Спробуйте написати хоку або чотиривірш про свій настрій.',
    category: 'Креативність',
    duration: 3,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-26',
    title: 'Улюблена пісня',
    description: 'Увімкніть та послухайте свій найулюбленіший трек.',
    category: 'Розваги',
    duration: 1,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-27',
    title: 'Смішний мем',
    description: 'Знайдіть та подивіться щось смішне для підняття настрою.',
    category: 'Розваги',
    duration: 2,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-28',
    title: 'Швидка гра',
    description: 'Зіграйте один раунд у будь-яку просту мобільну або браузерну гру.',
    category: 'Розваги',
    duration: 3,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-29',
    title: 'Вийти на балкон',
    description: 'Просто вийдіть на свіже повітря і зробіть кілька вдихів.',
    category: 'На вулиці',
    duration: 1,
    locationType: 'На вулиці',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-30',
    title: 'Подивитися на небо',
    description: 'Відволікайтеся від екрану і просто поспостерігайте за хмарами.',
    category: 'На вулиці',
    duration: 2,
    locationType: 'На вулиці',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-31',
    title: 'Фото природи',
    description: 'Знайдіть щось гарне (дерево, квітку, небо) і зробіть фото.',
    category: 'На вулиці',
    duration: 3,
    locationType: 'На вулиці',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-32',
    title: '5 глибоких вдихів',
    description: 'Зосередьтеся на диханні, щоб швидко заспокоїти нервову систему.',
    category: 'Відпочинок',
    duration: 1,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-33',
    title: 'Заплющити очі',
    description: 'Просто посидьте в тиші із заплющеними очима дві хвилини.',
    category: 'Відпочинок',
    duration: 2,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-34',
    title: 'Масаж долонь',
    description: 'Легкий самомасаж долонь і пальців для розслаблення.',
    category: 'Відпочинок',
    duration: 3,
    locationType: 'В приміщенні',
    costType: 'Безкоштовно',
    difficulty: 'Легко',
    rating: 4,
    isCustom: false,
  }
];
