export const DEMO_ACTIVITIES = [
  {
    id: 'demo-1',
    title: 'Go for a run in the park',
    description: 'Enjoy nature and get some exercise by running in your local park.',
    category: 'Sport',
    duration: 60,
    locationType: 'Outdoor',
    costType: 'Free',
    difficulty: 'Medium',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-2',
    title: 'Read a book',
    description: 'Pick up that book you\'ve been meaning to read and dive in.',
    category: 'Relaxation',
    duration: 120,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-3',
    title: 'Visit a local museum',
    description: 'Learn something new by exploring exhibits at a nearby museum.',
    category: 'Education',
    duration: 180,
    locationType: 'Indoor',
    costType: 'Paid',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-4',
    title: 'Try a new recipe',
    description: 'Find an interesting recipe online and cook it for dinner.',
    category: 'Creativity',
    duration: 90,
    locationType: 'Indoor',
    costType: 'Paid',
    difficulty: 'Medium',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-5',
    title: 'Go hiking',
    description: 'Find a trail and enjoy the great outdoors.',
    category: 'Outdoor',
    duration: 240,
    locationType: 'Outdoor',
    costType: 'Free',
    difficulty: 'Hard',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-6',
    title: 'Watch a classic movie',
    description: 'Pick a highly rated classic film and enjoy it with popcorn.',
    category: 'Entertainment',
    duration: 150,
    locationType: 'Indoor',
    costType: 'Paid',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-7',
    title: 'Do a home workout',
    description: 'Follow a yoga or HIIT video online.',
    category: 'Sport',
    duration: 45,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Medium',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-8',
    title: 'Learn to juggle',
    description: 'Grab three objects and look up a tutorial.',
    category: 'Education',
    duration: 30,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Hard',
    rating: 3,
    isCustom: false,
  },
  {
    id: 'demo-9',
    title: 'Listen to a podcast',
    description: 'Find an interesting podcast episode and learn something new while relaxing.',
    category: 'Education',
    duration: 30,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-10',
    title: '10-minute meditation',
    description: 'Sit quietly, focus on your breath, and clear your mind.',
    category: 'Relaxation',
    duration: 10,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-11',
    title: 'Quick stretch routine',
    description: 'Relieve tension by doing a full-body stretching routine.',
    category: 'Sport',
    duration: 15,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-12',
    title: 'Doodle or sketch',
    description: 'Grab a pencil and paper and draw whatever comes to mind.',
    category: 'Creativity',
    duration: 20,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-13',
    title: 'Short walk around the block',
    description: 'Get some fresh air with a quick walk outside.',
    category: 'Outdoor',
    duration: 20,
    locationType: 'Outdoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  },
  {
    id: 'demo-14',
    title: 'Drink tea in silence',
    description: 'Brew a cup of tea and drink it without any distractions.',
    category: 'Relaxation',
    duration: 15,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 5,
    isCustom: false,
  },
  {
    id: 'demo-15',
    title: 'Play a quick web game',
    description: 'Find a free browser game and play for a few minutes.',
    category: 'Entertainment',
    duration: 20,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 3,
    isCustom: false,
  },
  {
    id: 'demo-16',
    title: 'Write down 3 goals',
    description: 'Take a moment to write down three things you want to achieve this week.',
    category: 'Creativity',
    duration: 10,
    locationType: 'Indoor',
    costType: 'Free',
    difficulty: 'Easy',
    rating: 4,
    isCustom: false,
  }
];
